ADMIN_EMAIL = "smasterkelo@gmail.com"
ADMIN_PASSWORD = "@admin"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "ton_email_gmail@gmail.com"
SMTP_PASSWORD = "ton_mot_de_passe_application_gmail"
